version: "3.8"
services:
  db_develop:
    image: postgres:9.6
    container_name: "postgres"
    environment:
      - POSTGRES_DB=TestDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
volumes:
  postgres: